name:                data-analysis
version:             0.1.0.0
github:              "anthony-khong/data-analysis"
license:             BSD3
author:              "Anthony Khong"
maintainer:          "anthony.kusumo.khong@gmail.com"
copyright:           "-"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/anthony-khong/data-analysis#readme>

dependencies:
- base >= 4.7 && < 5
- Chart
- Chart-cairo
- Frames
- MissingH
- accelerate
- conduit
- csv
- flow
- foldl
- http-conduit
- microlens
- mtl
- numbers
- pipes
- random-fu
- random-source
- statistics
- tasty
- tasty-hunit
- vector

library:
  source-dirs: src

executables:
  data-analysis-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - data-analysis

tests:
  data-analysis-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - data-analysis
